### ISSUE TITLE
Keep receiving "TypeError: 'NoneType' object is not subscriptable" on CSV writer

### ISSUE THREAD

**Issue by Pahncake** [shivsondhi/export-spotify-playlists#1]
Hello, I'm new to github so I'm not sure if this is the correct spot for this, but I'm having an issue trying to write some data to a CSV.

I keep receiving "TypeError: 'NoneType' object is not subscriptable."

Here is the full error I am getting.

Traceback (most recent call last):
  File "spoti_api.py", line 199, in <module>
    main()
  File "spoti_api.py", line 53, in main
    write_playlist(playlist[1], playlist[0], mode)
  File "spoti_api.py", line 81, in write_playlist
    old_total = write_csv(filename, tracks)
  File "spoti_api.py", line 177, in write_csv
    track_url = track['external_urls']['spotify']
TypeError: 'NoneType' object is not subscriptable

I entered my valid CLI_ID & CLI_KEY and set the mode to CSV, as well as entered the filepath correctly for the output.  I apologize I am pretty new to python, and have never worked with an API before so I am fairly clueless about what I'm doing here.

Am I missing something? Thanks.

**Comment by shivsondhi** [comment]
Hello! Sorry, I only saw this issue a few days ago. I'm not sure if you're still looking for a solution, but I'll leave a reply anyway.

You usually get this error when you try to "access the elements" of a NoneType object. My guess is that in the last line of the error trace, `track` has a value of None. This could mean that your playlist is empty or one of the playlist items is missing track information. I have made some changes to the file that should fix these issues, but let me know if the problem persists, and I will try to help you out.
