### ISSUE TITLE
add album to csv file

### ISSUE THREAD

**Issue by lollilol** [shivsondhi/export-spotify-playlists#2]
i wanna add album to my csv file, how would i be able to do that?

**Comment by shivsondhi** [comment]
You will need to make some changes to `spotify_exporter.py`. Replace `user_playlist(id, uri)` on line 66 with the function: `album_tracks(album_id, limit)`. Check out the [spotipy documentation](https://spotipy.readthedocs.io/en/2.19.0/#api-reference) for the function. 

Depending on the object that `album_tracks()` returns, you might need to make some more minor changes on lines 66-86, but the rest can remain the same.
